name:                ipasir-minisat
version:             0.1.0.0
github:              "githubuser/ipasir-minisat"
license:             BSD3
author:              "Gerrit Marquardt"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ipasir-minisat#readme>

dependencies:
- base >= 4.7 && < 5
- ipasir
- monad-loops

library:
  source-dirs: src
  include-dirs: c_sources
  c-sources:
    - c_sources/main.c
    - c_sources/solver.c

tests:
  ipasir-minisat-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ipasir-minisat
    - QuickCheck
    - tasty
    - tasty-quickcheck
    - tasty-hunit
    - reflection

