name:                ipasir
version:             0.1.0.0
github:              "githubuser/ipasir"
license:             BSD3
author:              "Gerrit Marquardt, Philipp Dargel"
maintainer:          "example@example.com"
copyright:           "2019 Gerrit Marquardt"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/ipasir#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- array
- vector
- data-ordlist
- QuickCheck
- reflection
- transformers
- comonad
- ilist
- constraints

library:
  source-dirs: src

tests:
  ipasir-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ipasir
    - tasty
    - tasty-quickcheck
